services:
  postgres:
    image: postgres:latest
    container_name: forecast_budget_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
 
  api:
    build: .
    container_name: forecast_budget_api
    restart: always
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ORIGINS_ALLOWED: ${ORIGINS_ALLOWED}
    depends_on:
      - postgres
