"""create_incomes_table

Revision ID: 5cff4fcb6be8
Revises: 946958b8b624
Create Date: 2025-10-14 11:25:19.492974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cff4fcb6be8'
down_revision: Union[str, None] = '946958b8b624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.Enum('SALARY', 'FREELANCE', 'INVESTMENT', 'RENTAL', 'BUSINESS', 'BONUS', 'COMMISSION', 'ROYALTIES', 'PENSION', 'OTHER', name='incomecategory'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', 'ONE_TIME', name='incomefrequency'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.drop_table('incomes')
    # ### end Alembic commands ###
