name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: forecast_budget_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev gcc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/forecast_budget_test" >> $GITHUB_ENV
          echo "SECRET_KEY=test_secret_key_for_ci" >> $GITHUB_ENV
          echo "ENVIRONMENT=development" >> $GITHUB_ENV

      - name: Run Alembic migrations
        run: |
          alembic upgrade head

      - name: Run all tests
        run: |
          pytest tests/ -v --cov=app

      - name: Test summary
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "### ✅ Tests Passed!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "✅ All 257 tests passed (89% coverage)" >> $GITHUB_STEP_SUMMARY
            echo "✅ Ready for deployment to Railway" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Note:** Railway will automatically deploy this commit if tests pass." >> $GITHUB_STEP_SUMMARY
          else
            echo "### ❌ Tests Failed!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "❌ Some tests failed. Deployment blocked." >> $GITHUB_STEP_SUMMARY
          fi
